# "docker-compose.yml"이라는 이름을 사용하는게 좋다. 이유는 Dockerfile과 같음
# 보통 개발용, 테스트용, 프로덕션용 3가지로 사용

# docker-compose 파일 버전을 명시
version : "3"

# 컨테이너의 목록을 정의
services:
  app:
    # pull을 하거나, build를 할 때 이미지 파일로 만들 파일 명을 지정
    image: todolist-in-django:latest
    # build 명령어 지정
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      # 해당 URL 표기법이 표준 방식이다.
      DB_URL: mysql://kimdoyoung:01022074992@db:3306/todolist

  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: kimdoyoung
      MYSQL_PASSWORD: 01022074992
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: 01022074992
