# Generated by Django 2.2.2 on 2019-06-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Checked', models.IntegerField(default=0)),
                ('contents', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='published_date')),
                ('exp_date', models.DateTimeField(verbose_name='expire_date')),
            ],
        ),
    ]
