# Generated by Django 2.2.2 on 2019-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='is_Checked',
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_checked',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
