# Generated by Django 2.2.2 on 2019-07-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190701_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='exp_date',
            field=models.DateTimeField(null=True, verbose_name='expire_date'),
        ),
    ]
